# Documentation for TourPress WordPress theme.
#
# Author: Fahid Javid
#
# MKDOCS http://www.mkdocs.org/
# mkdocs-material http://squidfunk.github.io/mkdocs-material/
# License: The MIT License (MIT)

# Branding
site_name: TourPress WordPress Theme
site_description: 'Documentation for TourPress WordPress theme.'
site_author: 'Inspiry Themes'
site_url: 'https://inspirythemes.github.io/tp-doc/'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/InspiryThemes/tp-doc'

# Copyright
copyright: 'Copyright &copy; 2018 InspiryThemes'

theme: 'material'
theme_dir: 'mkdocs-material/material'

#use_directory_urls: false // to build direct links


extra:
  version: 1.0
  palette:
    primary: 'light-blue'
    accent: 'green'
  font:
      text: 'Open Sans'
      code: 'Ubuntu Mono'
  social:
      - type: 'twitter'
        link: 'https://twitter.com/inspirythemes'
      - type: 'facebook'
        link: 'https://www.facebook.com/InspiryThemes/'


extra_css:
  - 'stylesheets/style.css'

pages:
    - Introduction: index.md
    - Installation: installation.md
    - Import Demo Contents: import-demo-contents.md
    - Home Page:
      - Creating and Configuring Page: home/create-page.md
      - Home Page Settings:
        - Sections Manager: home/settings/sections-manager.md
        - Slider Area: home/settings/slider-area.md
        - Features: home/settings/features.md
        - Featured Packages: home/settings/featured-packages.md
        - Popular Destinations: home/settings/popular-destinations.md
        - Special Offers: home/settings/special-offers.md
        - Destination By Mood: home/settings/destination-by-mood.md
        - Blog Posts: home/settings/recent-from-blog.md
        - Testimonials: home/settings/testimonials.md
        - Explore Tours: home/settings/explore-tours.md
    - Tours:
      - Add New Tour: tour/add-tour.md
      - Create Tours Page: tour/create-tours-page.md
      - Tours Detils Page: tour/settings/tour-detail-page.md
      - Tours Price Format: tour/settings/price-format.md
      - Tours Slugs: tour/settings/tour-slugs.md
      - Tours Google Map API: tour/settings/tour-google-map-api.md
    - Other Pages: pages.md
    - Other Posts: posts.md
    - Widgets:
      - Recent Posts: widgets/recent-posts.md
      - Top Rated Tours: widgets/top-rated-tours.md
      - Address & Cotacts: widgets/address-contact.md
      - Social Share: widgets/soical-share.md
      - Tours Widget: widgets/tours.md
      - Tours Search: widgets/tours-search.md
    - WooCommerce Setup: woocommerce.md
    - Customization: customization.md


markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta