# Documentation for TourPress WordPress theme.
#
# Author: Fahid Javid
#
# MKDOCS http://www.mkdocs.org/
# mkdocs-material http://squidfunk.github.io/mkdocs-material/
# License: The MIT License (MIT)

# Branding
site_name: TourPress WordPress Theme
site_description: 'Documentation for TourPress WordPress theme.'
site_author: 'Fahid Javid'
site_url: 'https://fahidjavid.github.io/tp-doc'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/fahidjavid/tp-doc'

# Copyright
copyright: 'Copyright &copy; 2018 InspiryThemes'

theme: 'material'
theme_dir: 'mkdocs-material/material'

#use_directory_urls: false // to build direct links


extra:
  version: 1.0
  palette:
    primary: 'light-blue'
    accent: 'green'
  font:
      text: 'Open Sans'
      code: 'Ubuntu Mono'
  social:
      - type: 'twitter'
        link: 'https://twitter.com/inspirythemes'
      - type: 'facebook'
        link: 'https://www.facebook.com/InspiryThemes/'


extra_css:
  - 'stylesheets/style.css'

pages:
    - 1. Introduction: index.md
    - 2. Installation: installation.md
    - 3. Import Demo Contents: import-demo-contents.md
    - 4. Theme Settings: settings.md
    - 5. Create Pages: pages.md
    - 6. Add Contents: posts.md
    - 7. WooCommerce Setup: woocommerce.md
    - 8. Customization: customization.md



markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta